name: tradey

services:
  backend:
    container_name: tradey-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=${BACKEND_NODE_ENV}
      - PORT=${BACKEND_PORT}
      - CORS_ORIGIN=${BACKEND_CORS_ORIGIN}
      - FIREBASE_PROJECT_ID=vibe-hakaton
      - FIREBASE_ADMIN_KEY_PATH=/app/firebase-service-account.json
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - tradey-network
    volumes:
      - firebase-data:/app/firebase-data
      - ./backend/logs:/app/logs
      - ./backend/firebase-service-account.json:/app/firebase-service-account.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  frontend:
    container_name: tradey-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - tradey-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  tradey-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  firebase-data:
    driver: local
