version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tradey-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - tradey-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: tradey-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_URL=http://backend:5000/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - tradey-network
    restart: unless-stopped

networks:
  tradey-network:
    driver: bridge

