export const BELGRADE_MUNICIPALITIES = [
  'Čukarica',
  'Novi Beograd (New Belgrade)',
  'Palilula',
  'Rakovica',
  'Savski venac',
  'Stari grad (Old Town)',
  'Voždovac',
  'Vračar',
  'Zemun',
  'Grocka',
  'Barajevo',
  'Lazarevac',
  'Mladenovac',
  'Obrenovac',
  'Sopot',
  'Surčin',
]; 